services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    environment:
      - POSTGRES_DB:$POSTGRES_DB
      - POSTGRES_USER:$POSTGRES_USER
      - POSTGRES_PASSWORD:$POSTGRES_PASSWORD
      - TZ:'GMT'
      - PGTZ:'GMT'
    ports:
      - '5432:5432'